# FOSUserBundle Configuration
db_driver: orm
firewall_name: main
user_class: MinimalOriginal\SecurityBundle\Entity\User
from_email:
    address: "%mailer_sender_address%"
    sender_name: "%mailer_sender_name%"
